#!/bin/bash
#

PROJECT_DIR="$(git rev-parse --absolute-git-dir)/.."
GCOV="llvm-cov gcov"

set -e

if [ -f "${PROJECT_DIR}/.coveralls.yml" ]; then
    cd "${PROJECT_DIR}"

    echo "Running tests..."
    mkdir -p build
    cmake --build ./build -t test

    echo "Uploading coverage report..."
    if ! coveralls -i src -E .*/test.* -E .*_prod\..* \
              --gcov "${GCOV}"                   \
              --gcov-options '\-lp' > /dev/null &> /dev/null
    then
        echo "$0: coveralls failed. Please check your system."
    fi
else
    echo "Not updating coverage reports: configuration file not found"
fi

